### ISSUE TITLE
Update pipeline to use new nodejs approach in favour of Jenkinsfile, groovy etc.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#385]

**Comment by patricksimonian** [comment]
the node js pipeline is not quite ready for implementation yet. we will need to get some updates on it from @cvarjao

**Comment by sheaphillips** [comment]
let's move this to blocked.

**Comment by patricksimonian** [comment]
@cvarjao and i are planning to set aside some time next week to get this done.

**Comment by patricksimonian** [comment]
pending meeting up with @dkelsey and @cvarjao to talk about implementation, not date has been set yet

**Comment by patricksimonian** [comment]
so as an update, took a look at the node js pipeline as a service application.  It's looking promising but it still quite young. Because I'm leaving for vacay shortly here, i'm suggesting we forgo using this pipeline for now until I'm back and ready to maintain and issues that may arise from making the switch

**Comment by sheaphillips** [comment]
fine by me.

**Comment by patricksimonian** [comment]
Clecio and I are going to set aside time to setup the pipeline using the bcdk nodejs cli tool sometime this week
