### ISSUE TITLE
Review display of collections in search results from search on landing page.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#462]
Currently if a search result returns resources,  the results show the collection(s) that the resources are included in.  We should review/reconsider this behaviour so it's clear what we're communicating.  Also, there is an apparent bug where clicking on the collection from this view does not go anywhere (while clicking on an individual resource below goes to the resource).

**Comment by patricksimonian** [comment]
what are your thoughts on the end goal for this task?

**Comment by patricksimonian** [comment]
I've found some great findings:

Gatsby has some amazing new provisions since version 2.2 which allows us to use the gatsby framework itself to get to our goal of a 'graph' based registry. 

In addition I have played around with seperating registry files and generating plugin configurations based off of them and this is also possible. 

Siphon has been removed and instead the devhub plugin can be thought of a 'funnel' it is a transformer plugin that works like an abstract class factory. It can normalize any source/transformer plugin based on an interface that is passed in as config. 

The design system can be upgraded to mdx type files. Infact almost all documentation can be upgraded to use mdx files.
