### ISSUE TITLE
Update font from Noto Sans to BC Sans

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/devhub-app-web#879]
Now that we have the BC Sans font file, we should update DevHub to the proper font file. Access to font file download is here https://developer.gov.bc.ca/Design-System/Typography 

We also need to stop using the google api in our iframe examples in the design system and switch to BC Sans

**Comment by patricksimonian** [comment]
the iframe thing is a bit tricky. Some investigation will be needed to done to see if we can source font files from the design system repo in that iframe, load it into the Devhub and check if it works. If not, I feel the best solution would be to have the font hosted so that the iframes can grab the fonts more easily.

**Comment by dlevineBC** [comment]
If the font is hosted on devhub could it be read from there, rather than using the typography.js? I'm not super aware of the limitations that iframes

**Comment by patricksimonian** [comment]
@jas29 this could be one to look into. There is an npm package with installation instructions of changing to BC Sans font. 

the package is called `@bcgov/bc-sans`

**Comment by patricksimonian** [comment]
closing as this  has become stale
